### ISSUE TITLE
ipv6 support needed

### ISSUE THREAD

**Issue by gattytto** [php/pecl-mail-imap#14]
hello, I explain the situation in this particular issue:
https://github.com/Z-Hub/Z-Push/issues/126

I sincerely hope the geniuses maintaining this repo can help us overcome the current situation.

thank you so much in advance

@derickr  @petk @nielsdos @Girgias @remicollet @cmb69

**Comment by ndossche** [comment]
The lack of support comes from the c-client library that the imap extension uses under the hood.
That library hasn't been maintained properly since the 2010s, which was the reason for unbundling imap from PHP. This issue would have to be fixed there but given the decade+ lack of maintenance this will never happen.
You should drop this extension and use a PHP userland solution instead.

**Comment by cmb69** [comment]
See also https://github.com/php/pecl-mail-imap/issues/12#issuecomment-2373407408.

**Comment by gattytto** [comment]
thank you all so much for your answers! I'll go cry to that corner over there
